export const origin = 'https://www.norcalveterans.org';
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const h=escapeHtml;
const mark='<img class="project-logo" src="/published-assets/norcal-veterans.png?v=logo-20260913-1" alt="NorCal Veterans" width="1254" height="1254" decoding="async">';
function shellBase(title,description,content,{path='/',detail=false}={}) {
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)}</title><meta name="description" content="${h(description)}"><link rel="canonical" href="${origin}${h(path)}"><meta property="og:type" content="website"><meta property="og:title" content="${h(title)}"><meta property="og:description" content="${h(description)}"><meta property="og:url" content="${origin}${h(path)}">${detail?'':`<meta property="og:image" content="${origin}/ysv-logo.png?v=logo-20260903-1"><meta property="og:image:width" content="1254"><meta property="og:image:height" content="1254"><meta property="og:image:alt" content="Yolo Solano Veterans logo">`}<meta name="twitter:card" content="summary"><meta name="twitter:title" content="${h(title)}"><meta name="twitter:description" content="${h(description)}">${detail?'':`<meta name="twitter:image" content="${origin}/ysv-logo.png?v=logo-20260903-1"><meta name="twitter:image:alt" content="Yolo Solano Veterans logo">`}<meta name="theme-color" content="#123c74"><link rel="icon" href="/ysv-logo.png?v=logo-20260903-1" type="image/png"><link rel="stylesheet" href="/styles.css?v=officers-20260903-1"><script src="/app.js?v=officers-20260903-1" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="topline"><div class="wrap">A growing local resource · Yolo &amp; Solano counties <a href="https://www.veteranscrisisline.net/">Crisis support: 988, then press 1 ↗</a></div></div><header class="header wrap"><a href="/" class="brand" aria-label="Yolo Solano Veterans">${mark}</a><nav aria-label="Main navigation"><a href="/" ${path==='/'?'aria-current="page"':''}>Find an organization</a><a href="/events" ${path==='/events'?'aria-current="page"':''}>Events</a><a href="/resources" ${path==='/resources'?'aria-current="page"':''}>Resources</a><a href="/about" ${path==='/about'?'aria-current="page"':''}>About the directory</a><a class="nav-workspace" href="/for-organizations">For organizations <span aria-hidden="true">↗</span></a><a class="nav-workspace" href="/hq">Organization sign-in</a></nav></header><main id="main">${content}</main><footer><div class="wrap footer-inner"><div><a class="footer-brand" href="/">Yolo Solano Veterans</a><p>Local connections. Shared purpose.</p></div><div class="footer-links"><a href="/resources">Veteran resources</a><a href="/about#sources">Our sources</a><a href="/data.json">Directory data</a><a href="/for-organizations">Share an update</a></div></div><div class="wrap fineprint">An independent community directory. Listings do not imply endorsement or partnership. Review dates and sources appear on individual listings; confirm current details with each organization.</div></footer></body></html>`;
}
export function shell(title,description,content,options={}){
 const path=options.path||'/',html=shellBase(title,description,content,options),share=`<a href="/share" ${path==='/share'?'aria-current="page"':''}>Share a program</a>`;
 return html.replace('<a href="/about"',share+'<a href="/about"').replace('<link rel="stylesheet" href="/styles.css?v=officers-20260903-1">','<link rel="stylesheet" href="/styles.css?v=event-cards-20260921-1">').replace('<script src="/app.js?v=officers-20260903-1" defer></script>','<script src="/app.js?v=profiles-20260913-1" defer></script>').replace('<a href="/for-organizations">Share an update</a>','<a href="/share">Share a program</a><a href="/for-organizations">Share an update</a>').replace('<a class="button outline" href="#officers">View officers</a>','');
}
