import {shell,escapeHtml,origin} from '../../shared/public-shell.mjs';
import {sanitizePublicEvent} from './serialization.mjs';
import {publicMonthCalendar} from './calendar.mjs';
const pe=escapeHtml;
const publicDate=s=>new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeStyle:'short',timeZone:'America/Los_Angeles'}).format(new Date(s));
const publicEventDate=v=>v.date_only?new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeZone:'America/Los_Angeles'}).format(new Date(v.start_at))+' · Time to be confirmed':publicDate(v.start_at);
const pacificDayKey=s=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'America/Los_Angeles'}).format(new Date(s));
const isVfw8151Meeting=v=>v.kind==='Organization meeting'&&v.organization_id==='vfw-ca-8151';
export const upcomingEvents=(events,now=Date.now())=>events.map(sanitizePublicEvent).filter(v=>v&&v.status==='published'&&(v.date_only?pacificDayKey(v.start_at)>=pacificDayKey(now):Date.parse(v.end_at||v.start_at)+(!v.end_at?86400000:0)>=now)).sort((a,b)=>Date.parse(a.start_at)-Date.parse(b.start_at));
function eventReview(v){
 if(v.source_kind==='project_team')return `<span class="label">Project team update</span><h2>Check before you go.</h2><p>${pe(v.source_note||'Event details supplied by the project team.')}</p><p>${v.source_checked&&v.source_url?'Supporting source reviewed '+pe(v.source_checked)+'.':'Independent source verification is pending.'}</p>`;
 if(v.source_checked&&v.source_url)return `<span class="label">Published source checked</span><h2>Check before you go.</h2><p>Source reviewed ${pe(v.source_checked)}. This listing has not been directly confirmed with the organizer.</p>`;
 return '<span class="label">Verification pending</span><h2>Check before you go.</h2><p>This published listing has no recorded source review. Confirm the details directly with the organizer.</p>';
}
function eventCard(v){const listed=isVfw8151Meeting(v);return `<article class="panel event-card"><div class="row-between"><span class="eyebrow">${pe(v.kind)}</span><span class="label">${pe(v.county)} County</span></div><h2>${listed?pe(v.title):`<a href="/events/${pe(v.id)}">${pe(v.title)}</a>`}</h2><p class="event-time">${pe(publicEventDate(v))}</p><p>${pe(v.venue)}</p><p>${pe(v.description)}</p>${listed?'<span class="small-note">Listed meeting — confirm details with the post.</span>':`<a href="/events/${pe(v.id)}">Event details &amp; attendance →</a>`}</article>`;}
export function eventsPagePublic(url,events){const county=['Yolo','Solano'].includes(url.searchParams.get('county'))?url.searchParams.get('county'):'',upcoming=upcomingEvents(events).filter(v=>!county||v.county===county);return shell('Community events | Yolo Solano Veterans','Find published veteran community events, remembrance ceremonies and volunteer opportunities in Yolo and Solano counties.',`<section class="wrap about-page"><span class="eyebrow">MAKE TIME FOR COMMUNITY</span><h1>Show up.<br><em>Connect. Give back.</em></h1><p class="intro">A shared calendar of published local events and opportunities to serve.</p>${publicMonthCalendar(url,events,{path:'/events',title:'Community calendar'})}<section class="panel"><span class="eyebrow">REMEMBER &amp; HONOR</span><h2>Memorial Day services</h2><p>Find services by city, with verified past schedules and 2027 details to be confirmed.</p><a class="button outline" href="/memorial-day">Explore the city-by-city guide →</a></section><form class="panel inline-form" method="get"><label for="event-county">Explore by county</label><select id="event-county" name="county"><option value="">Yolo &amp; Solano</option><option value="Yolo" ${county==='Yolo'?'selected':''}>Yolo</option><option value="Solano" ${county==='Solano'?'selected':''}>Solano</option></select><button class="button">Show events</button><a href="/events.ics">Download calendar ↓</a></form><p class="results-note">${upcoming.length} upcoming listings · Pacific time. Open each listing for its source and verification status; confirm schedule, accessibility and attendance rules with the host. Calendar downloads are a snapshot and do not refresh automatically.</p><div class="two-up">${upcoming.length?upcoming.map(eventCard).join(''):'<div class="panel"><h2>No upcoming listings for this selection.</h2><p>More events are being verified. Browse both counties or share a proposed event below.</p></div>'}</div><div class="partner-strip panel"><h2>Have something to share?</h2><p>Send the public details and organizer’s source. A review comes before publication.</p><a class="button light" href="/for-organizations?kind=event">Propose an event →</a></div></section>`,{path:'/events'});}
export function eventDetail(v,organizations=[]){const host=organizations.find(r=>r.id===v.organization_id),past=!upcomingEvents([v]).length;return shell(`${v.title} | Yolo Solano Veterans`,v.description,`<section class="wrap detail-page"><a class="back" href="/events">← All events</a><div class="profile-heading"><span class="eyebrow">${pe(v.kind)} · ${pe(v.county)} COUNTY</span><h1>${pe(v.title)}</h1>${past?'<span class="label amber">Past event</span>':''}<p>${pe(v.description)}</p></div><div class="profile-grid"><section class="panel"><h2>Plan your visit</h2><dl><div><dt>When</dt><dd>${pe(publicEventDate(v))}${!v.date_only&&v.end_at?'<br>Ends '+pe(publicDate(v.end_at)):''}</dd></div><div><dt>Where</dt><dd>${pe(v.venue)}<br><a href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(v.venue)}" target="_blank" rel="noopener noreferrer">Open venue in Maps ↗</a></dd></div><div><dt>Who can attend?</dt><dd>${pe(v.audience)}</dd></div><div><dt>Organizer</dt><dd>${pe(v.organizer)}${host?`<br><a href="/organizations/${host.id}">View related organization →</a>`:''}</dd></div></dl>${v.time_note?`<p class="small-note">${pe(v.time_note)}</p>`:''}<div class="profile-actions">${v.source_url?`<a class="button" href="${pe(v.source_url)}" target="_blank" rel="noopener noreferrer">${v.source_kind==='project_team'?'Organizer website':'Organizer details / registration'} ↗</a>`:''}<a class="button outline" href="/events.ics?event=${pe(v.id)}">Add to calendar ↓</a></div></section><aside class="panel">${eventReview(v)}<p>Follow the organizer’s latest instructions for registration, accessibility, weather changes and cancellations.</p><a href="/for-organizations?kind=event">Suggest a correction →</a></aside></div></section>`,{path:'/events/'+v.id,detail:true});}
const icsEscape=s=>String(s||'').replaceAll('\\','\\\\').replace(/\r?\n/g,'\\n').replaceAll(';','\\;').replaceAll(',','\\,');
const utc=s=>new Date(s).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
function foldICS(line){const lines=[];let current='',bytes=0;for(const c of line){const n=new TextEncoder().encode(c).length;if(bytes+n>74){lines.push(current);current=' ';bytes=1;}current+=c;bytes+=n;}lines.push(current);return lines.join('\r\n');}
export function eventCalendar(events){events=events.map(sanitizePublicEvent).filter(Boolean);const stamp=utc(new Date());const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Yolo Solano Veterans//Community Calendar//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:Yolo Solano Veterans'];for(const v of events){if(v.status!=='published')continue;const day=pacificDayKey(v.start_at),nextDay=new Date(Date.parse(day+'T00:00:00Z')+86400000).toISOString().slice(0,10),schedule=v.date_only?['DTSTART;VALUE=DATE:'+day.replaceAll('-',''),'DTEND;VALUE=DATE:'+nextDay.replaceAll('-','')]:['DTSTART:'+utc(v.start_at),...(v.end_at?['DTEND:'+utc(v.end_at)]:[])],note=(v.date_only?'Time to be confirmed. This calendar entry reserves the date; event hours have not been announced.\n':'')+v.description+'\n'+v.audience+(v.source_kind==='project_team'?'\n'+(v.source_note||'Details supplied by the project team.'):'')+(v.source_url?'\nConfirm latest details: '+v.source_url:'');lines.push('BEGIN:VEVENT','UID:'+icsEscape(v.id)+'@yolo-county-veterans','DTSTAMP:'+stamp,...schedule,'SUMMARY:'+icsEscape(v.title+(v.date_only?' — Time to be confirmed':'')),'DESCRIPTION:'+icsEscape(note),'LOCATION:'+icsEscape(v.venue),...(!isVfw8151Meeting(v)?['URL:'+origin+'/events/'+encodeURIComponent(v.id)]:[]),'END:VEVENT');}lines.push('END:VCALENDAR');return lines.map(foldICS).join('\r\n')+'\r\n';}
