import {extraSources,extraRecords} from './research-additions.mjs';
export const checked = '2026-09-02';
const source = (id,title,publisher,url,fields,published=null,notes=null) => ({id,title,publisher,url,fields,published_date:published,accessed_date:checked,notes});
export const sources = [
 source('rememberavet-home','RememberAVet Wreath Project','RememberAVet','https://www.wreathproject.org/',['identity','mailing_address','public_contacts','program']),
 source('vets-official','Veterans Equine Therapy - official website','Veterans Equine Therapy','https://www.veteransequinetherapy.com/',['identity','public_contacts','program','nonprofit_self_description'],null,'Describes the organization as a nonprofit supporting veterans through equine-assisted therapy. Lists general organization contacts; current intake, schedule and visit location are not established.'),
 ...extraSources,
 source('west-sac','West Sacramento VFW','VFW Post 8762','https://westsacvfw.com/',['identity','public_contacts','member_information']),
 source('benicia-vfw','Benicia VFW','VFW Post 3928','https://www.beniciavfw.org/',['identity','member_information']),
 source('vacaville-vfw','Vacaville VFW','VFW Post 7244','https://www.vfwpost7244.org/',['identity','venue','public_contacts']),
 source('legion-77','Sacramento Valley veterans outreach','The American Legion','https://www.legion.org/information-center/news/membership/2026/april/veterans-benefits-assistance-coming-to-sacramento-area',['identity','address','past_event'],'2026-04', 'April 17-19 outreach is historical, not continuing service hours.'),
 source('vfw-7143-official','VFW Post 7143 in Esparto CA','VFW Post 7143','https://vfw7143.org/di/vfw/v2/default.asp',['identity','city','mailing_address','website','programs'],null,'Official post website. The published PO box is a mailing address, not a visitor location; current meeting details still require confirmation.'),
 source('vacavets','Veterans Memorial Building and calendar','Vacaville Veterans Memorial Building','https://www.vacavets.org/',['venue','meetings','events'],null,'Meeting venue; hall contact is not a detachment contact.'),
 source('mcl-funding','Marine Corps League contribution, File 25-292','Solano County','https://solano.legistar.com/LegislationDetail.aspx?GUID=A35327E8-C770-4843-97BB-7356132DF1C5&ID=7319441&Options=&Search=',['identity','historical_activities'],'2025-04-22'),
 source('toys-yolo','Mail Services Toy Drive 2025','UC Davis Supply Chain Management','https://supplychain.ucdavis.edu/events/mail-services-toy-drive-2025',['campaign','service_area','past_event'],'2025', 'December 1-11, 2025 collection dates are historical.'),
 source('toys-chamber','Community organizations directory','Davis Chamber of Commerce','https://web.davischamber.com/davis/Community-Organizations?ysort=true',['campaign_link','public_contact'],null,'Chamber directory; campaign confirmation needed.'),
 source('toys-solano','Solano County campaign','Marine Toys for Tots','https://solano-county-ca.toysfortots.org/local-coordinator-sites/lco-sites/default.aspx?nPageID=0&nPreviewInd=0&nRedirectInd=3',['campaign','service_area','intake','partnership'],null,'Official search extraction; direct opening unavailable. Page reports 2025 activity; 2026 dates unverified.'),
 source('dav-21','Ozie Boler Chapter 21','DAV','https://davwebsites.dav.org/ca/21/SystemPages/Home.aspx',['identity','meeting_venue','meetings'],null,'Phone conflicts and erroneous template text excluded.'),
 source('dav-84-contact','Chapter 84 contact and meetings','DAV Chapter 84','https://www.cadav84.org/contact',['identity','address','meetings','email','audience','accessibility','venue_contact'],null,'The phone 707-447-6354 is explicitly listed for the Veterans Memorial Building and hall rental, not as the chapter contact.'),
 source('dav-84-area','Who we serve','DAV Chapter 84','https://www.cadav84.org/about-who-we-serve',['service_area','audience']),
 source('yolo-vso','Veterans Services Office','Yolo County','https://www.yolocounty.gov/government/general-government-departments/health-human-services/adults/veterans-service-office',['identity','service_categories','address','phone','hours','audience','referrals']),
 source('solano-vso','Veterans Services','Solano County','https://www.solanocounty.gov/government/veterans-services',['identity','service_categories','address','phone','hours','audience','partnership']),
 source('vbc-national','Veterans Beer Club','Veterans Beer Club','https://veteransbeerclub.org/',['identity','mission','audience','chapters'],null,'The national organization site includes Yolo-Solano chapter imagery and describes the club mission and audience.'),
 source('vbc-yolo-solano-resource','Local Resources','VFW Post 8151','https://vfw8151.org/di/vfw/v2/default.asp?nid=4',['local_chapter_identity'],null,'Official VFW post resource page lists Veterans Beer Club Yolo-Solano Chapter.')
];
function record(id,name,type,city,county,address,meeting,website,source_ids,extra={}) {
 return {id,verified_name:name,organization_type:type,entity_kind:'organization',city,location_county:county,service_area:null,address:address?{text:address,type:'meeting_venue',map_eligible:true}:null,public_contacts:{phone:null,email:null,website},hours:null,meeting_schedule:meeting,timezone:'America/Los_Angeles',service_categories:[],audience:null,eligibility:null,event_information:null,referral_notes:'Contact the organization to confirm available services and the appropriate next step.',partnership_notes:null,officers:[],officers_status:'not_verified',member_information:null,source_ids,last_verified_date:checked,verification_method:'public_source_review',organization_confirmed_at:null,confidence:'medium',missing_data_flags:[],...extra};
}
export const records = [
 record('rememberavet','RememberAVet - Wreath Project','Veteran remembrance program','Winters','Yolo',null,null,'https://www.wreathproject.org/',['rememberavet-home','rememberavet-volunteer-2026','rememberavet-boughs-2026'],{address:{text:'PO Box 773, Winters, CA 95694',type:'mailing',map_eligible:false},public_contacts:{phone:null,email:'WreathProject@yahoo.com',website:'https://www.wreathproject.org/'},service_area:{counties:['Solano'],cities:['Dixon'],notes:'Holiday bough activities at Sacramento Valley National Cemetery in Dixon; the project publishes a Winters mailing address.'},service_categories:['Remembrance','Volunteering'],member_information:'Coordinates fundraising and volunteers for holiday bough placement and cleanup at Sacramento Valley National Cemetery in Dixon. Its Winters address is a mailing address, not a visitor office. RememberAVet bough activities and the cemetery’s Wreaths Across America ceremony are separate programs.',audience:'Community volunteers; check each activity’s participation instructions.',confidence:'high',missing_data_flags:['office_hours_unknown','organization_confirmation_pending']}),
 record('little-reata-veterans','Veterans Equine Therapy (VETs)','Equine program provider','Davis','Yolo',null,null,'https://www.veteransequinetherapy.com/',['vets-official'],{display_name_update:{method:'authenticated_project_update',date:checked,scope:'Display name supplied through an authenticated project update; organization information reviewed against its official website.'},public_contacts:{phone:'530-867-5150',email:'vets@veteransequinetherapy.com',website:'https://www.veteransequinetherapy.com/'},service_categories:['Equine-assisted therapy','Veteran support'],member_information:'Veterans Equine Therapy (VETs) describes itself as a nonprofit organization supporting veterans through equine-assisted therapy. Use its official website or general organization contact to ask about current participation, schedules and visits.',audience:'Veterans; current eligibility and participation details need confirmation.',missing_data_flags:['current_intake_unconfirmed','schedule_unconfirmed','visit_location_unconfirmed','participation_details_unconfirmed']}),
 record('veterans-beer-club-yolo-solano','Veterans Beer Club Yolo-Solano','Veterans Beer Club',null,'Yolo',null,'Second Thursday of each month at a rotating Yolo or Solano County brewery. Confirm the current venue before attending.','https://veteransbeerclub.org/',['vbc-national','vbc-yolo-solano-resource'],{display_name_update:{method:'authenticated_project_update',date:'2026-09-04',scope:'Chapter name, meeting pattern and official chapter social links supplied by an authenticated project editor.'},service_area:{counties:['Yolo','Solano'],cities:[],notes:'Yolo and Solano counties; monthly venue rotates between local breweries.'},service_categories:['Veteran networking','Career connections','Community outreach'],member_information:'A local chapter of Veterans Beer Club, an informal networking community centered on camaraderie, career connections and community outreach.',audience:'Veterans, active duty service members, reservists, Guard members, military retirees and spouses. Recruiters are welcome at national VBC events.',referral_notes:'Use the chapter social pages to confirm the brewery and time for the next second-Thursday gathering.',confidence:'high',missing_data_flags:['next_meeting_venue_unconfirmed','instagram_link_unverified']}),
 ...extraRecords,
 record('vfw-ca-8762','West Sacramento VFW Post 8762','VFW','West Sacramento','Yolo','905 Drever Street, West Sacramento, CA 95691','Second Wednesday � 6:30 p.m.','https://westsacvfw.com/',['west-sac'],{public_contacts:{phone:'916-371-7245',email:null,website:'https://westsacvfw.com/'},service_categories:['Veteran community','Benefits navigation'],member_information:'Post website links to benefits assistance and hall rentals. Confirm how assistance is provided.',audience:'Veterans, families and community; program rules need confirmation.',missing_data_flags:['service_area_unknown','eligibility_unconfirmed','hours_unknown']}),
 record('legion-ca-77','Yolo American Legion Post 77','American Legion','Woodland','Yolo','523 Bush Street, Woodland, CA 95695',null,null,['legion-77'],{member_information:'Woodland post documented as the host of an April 2026 veterans outreach session.',event_information:{status:'past',text:'Benefits outreach held April 17-19, 2026. This does not establish ongoing service hours.',source_id:'legion-77'},missing_data_flags:['routine_contact_missing','meeting_schedule_missing','service_area_unknown']}),
 record('vfw-ca-7143','Western Yolo VFW Post 7143','VFW','Esparto','Yolo',null,null,'https://vfw7143.org/',['vfw-7143-official'],{address:{text:'PO Box 232, Esparto, CA 95627',type:'mailing',map_eligible:false},public_contacts:{phone:null,email:null,website:'https://vfw7143.org/'},member_information:'The official Post 7143 website identifies the organization in Esparto. Use the post website to confirm current meetings, activities and attendance details.',missing_data_flags:['meeting_venue_unconfirmed','meeting_schedule_unconfirmed','general_organization_contact_unconfirmed','service_area_unknown']}),
 record('mcl-yolo','Marine Corps League - Yolo County Detachment 627','Marine Corps League','Woodland','Yolo','500 Bush Street, Woodland, CA 95695',null,null,[],{display_name_update:{method:'authenticated_project_update',date:checked,scope:'Detachment number supplied through an authenticated project clarification; current contact and meeting details remain unconfirmed.'},member_information:'Meetings have been listed at the Woodland Elks Lodge. Confirm current meeting and visitor details through an organization contact.',missing_data_flags:['public_source_withheld_for_privacy','meeting_schedule_unconfirmed','local_contact_missing','service_area_unknown','hours_unknown']}),
 record('toys-yolo','Toys for Tots - Yolo County','Toys for Tots',null,'Yolo',null,null,'https://woodland-ca.toysfortots.org/',['toys-yolo','toys-chamber'],{entity_kind:'seasonal_campaign',service_area:{counties:['Yolo'],cities:[],notes:'Yolo County children; 2026 campaign rules not yet verified.'},service_categories:['Holiday toy assistance','Volunteering'],audience:'Children and families in Yolo County.',member_information:'Seasonal toy collection and distribution program. Follow the campaign for current application instructions.',event_information:{status:'past',text:'UC Davis collection ran December 1-11, 2025. Family application and distribution dates for 2026 remain unverified. See the shared calendar for campaign-related community events.',source_id:'toys-yolo'},partnership_notes:'UC Davis Mail Services collection partnership documented for 2025.',missing_data_flags:['campaign_page_unavailable','2026_dates_missing','address_missing','application_rules_unknown']}),
 record('vso-yolo','Yolo County Veterans Services Office','County Veterans Office','Woodland','Yolo','137 N. Cottonwood Street, Woodland, CA',null,'https://www.yolocounty.gov/government/general-government-departments/health-human-services/adults/veterans-service-office',['yolo-vso'],{address:{text:'137 N. Cottonwood Street, Woodland, CA',type:'service_office',map_eligible:true},public_contacts:{phone:'530-406-4850',email:null,website:'https://www.yolocounty.gov/government/general-government-departments/health-human-services/adults/veterans-service-office'},service_area:{counties:['Yolo'],cities:[],notes:'County veterans office; confirm requirements for the specific benefit.'},service_categories:['Benefits navigation','Claims assistance','Referrals'],hours:'Monday-Thursday � 7:30 a.m.-4 p.m.; lunch closure noon-1 p.m.; Friday closed to public.',audience:'Veterans, dependents and survivors.',member_information:'County benefit counseling, claims support and referrals. Contact the office for appointments and outreach locations.',confidence:'high',missing_data_flags:['program_eligibility_varies']}),
 record('vfw-ca-3928','Benicia VFW Post 3928','VFW','Benicia','Solano','1150 1st Street, Benicia, CA 94510','First Wednesday � 7 p.m.','https://www.beniciavfw.org/',['benicia-vfw'],{public_contacts:{phone:null,email:null,website:'https://www.beniciavfw.org/'},member_information:'Local veteran and community organization. Its website describes work with its Auxiliary.',missing_data_flags:['service_area_unknown','program_details_unconfirmed','hours_unknown']}),
 record('vfw-ca-7244','Lt. Michael Libonati Jr. VFW Post 7244','VFW','Vacaville','Solano','549 Merchant Street, Vacaville, CA 95688','Second Tuesday � 7 p.m.','https://www.vfwpost7244.org/',['vacaville-vfw'],{public_contacts:{phone:null,email:'vfwpost7244@gmail.com',website:'https://www.vfwpost7244.org/'},member_information:'Post gatherings at Vacaville Veterans Hall. Use the post’s general email or website for organization inquiries. For Veterans Memorial Building or hall-rental inquiries, the separate public venue number is 707-447-6354.',missing_data_flags:['multiple_contact_roles','service_area_unknown','hours_unknown']}),
 record('vfw-ca-1123','Carl H. Kreh VFW Post 1123','VFW','Vallejo','Solano','420 Admiral Callaghan Lane, Vallejo, CA 94591',null,null,[],{public_contacts:{phone:null,email:null,website:null},member_information:'Local veterans organization. Current organization contact details and activities need confirmation.',missing_data_flags:['public_source_withheld_for_privacy','meeting_schedule_unconfirmed','general_organization_contact_unconfirmed','website_missing','service_details_missing','eligibility_unconfirmed']}),
 record('vfw-ca-2333','Simmons-Sheldon VFW Post 2333','VFW','Suisun City','Solano','427 Main Street, Suisun City, CA 94585',null,null,[],{public_contacts:{phone:null,email:null,website:null},member_information:'Local veterans organization. Current organization contact details and activities need confirmation.',missing_data_flags:['public_source_withheld_for_privacy','meeting_schedule_unconfirmed','general_organization_contact_unconfirmed','website_missing','service_details_missing','eligibility_unconfirmed']}),
 record('legion-ca-101','American Legion Post 101 - Benicia','American Legion','Benicia','Solano','1150 1st Street, Benicia, CA 94510',null,null,[],{public_contacts:{phone:null,email:null,website:null},member_information:'Local American Legion post. Current gatherings, programs and a general organization contact need confirmation.',missing_data_flags:['public_source_withheld_for_privacy','meeting_schedule_unconfirmed','program_availability_unconfirmed','service_area_unknown']}),
 record('legion-ca-603','American Legion Post 603 - Manuel Quezon','American Legion','Vallejo','Solano','420 Admiral Callaghan Lane, Vallejo, CA 94591',null,null,[],{public_contacts:{phone:null,email:null,website:null},member_information:'Local American Legion post. A general organization contact for membership and activities has not been confirmed.',missing_data_flags:['public_source_withheld_for_privacy','meeting_schedule_unconfirmed','service_area_unknown','email_missing']}),
 record('mcl-ca-1486','Marine Corps League - Charles "Bud" Hallam Detachment 1486','Marine Corps League','Vacaville','Solano','549 Merchant Street, Vacaville, CA 95688','First Wednesday � 7 p.m.','https://www.solanocountymcl1486.org/',['vacavets','mcl-funding'],{member_information:'Meets at Vacaville Veterans Hall, 549 Merchant Street. Confirm current meeting details through the public venue or organization website.',event_information:{status:'confirm_with_organizer',text:'Check the venue calendar for the next detachment meeting.',source_id:'vacavets'},missing_data_flags:['local_contact_missing','service_area_unknown']}),
 record('toys-solano','Toys for Tots - Solano County','Toys for Tots',null,'Solano',null,null,'https://solano-county-ca.toysfortots.org/local-coordinator-sites/lco-sites/default.aspx?nPageID=0&nPreviewInd=0&nRedirectInd=3',['toys-solano'],{entity_kind:'seasonal_campaign',service_area:{counties:['Solano'],cities:[],notes:'Solano campaign; city-level exclusions unverified.'},service_categories:['Holiday toy assistance','Volunteering'],audience:'Children and families; current application rules need confirmation.',member_information:'The campaign provides family and agency request routes and toy-drop participation. Submit any required documents only to the campaign.',event_information:{status:'not_verified',text:'2026 application and distribution dates have not been verified.',source_id:'toys-solano'},partnership_notes:'Campaign lists nonprofit/agency and collection-site participation.',missing_data_flags:['2026_dates_missing','service_location_missing','phone_email_missing','eligibility_incomplete']}),
 record('dav-ca-21','DAV - Ozie Boler Chapter 21','DAV','Vallejo','Solano','420 Admiral Callaghan Lane, Vallejo, CA 94591','Fourth Saturday � 10 a.m.','https://davwebsites.dav.org/ca/21/SystemPages/Home.aspx',['dav-21'],{member_information:'DAV-hosted page lists this chapter and its meeting. Public phone listings conflict; use the official page to confirm the best contact.',missing_data_flags:['phone_conflict','service_area_unknown','local_service_capacity_unconfirmed']}),
 record('dav-ca-84','DAV Chapter 84 - Vacaville','DAV','Vacaville','Solano','549 Merchant Street, Vacaville, CA 95688','Second Saturday � 10 a.m. � except December','https://www.cadav84.org/',['dav-84-contact','dav-84-area','vacavets'],{public_contacts:{phone:null,email:'cadisabledvets84@gmail.com',website:'https://www.cadav84.org/'},service_area:{counties:['Solano'],cities:['Cordelia','Travis AFB','Suisun City','Fairfield','Vacaville','Dixon'],notes:'Northern Solano and intervening unincorporated areas; not all of Solano County.'},audience:'All veterans may visit meetings. Chapter membership is described separately as for VA-rated disabled veterans.',service_categories:['Veteran community','Benefits navigation','Referrals'],member_information:'Use the chapter’s general email or website for organization inquiries. For Veterans Memorial Building or hall-rental inquiries, use the separate venue contact 707-447-6354. Enter through the back door; the chapter describes elevator access to the meeting hall.',confidence:'high',missing_data_flags:['multiple_contact_roles','stale_event_feed']}),
 record('vso-solano','Solano County Veterans Service Office','County Veterans Office','Fairfield','Solano','675 Texas Street, Suite 4700, Fairfield, CA 94533',null,'https://www.solanocounty.gov/government/veterans-services',['solano-vso'],{address:{text:'675 Texas Street, Suite 4700, Fairfield, CA 94533',type:'service_office',map_eligible:true},public_contacts:{phone:'707-784-6590',email:null,website:'https://www.solanocounty.gov/government/veterans-services'},service_area:{counties:['Solano'],cities:[],notes:'County veterans office; individual program rules vary.'},service_categories:['Benefits navigation','Claims assistance','Referrals'],hours:'Monday-Thursday � 9 a.m.-4 p.m.; lunch closure noon-1 p.m.',audience:'Veterans, dependents and survivors.',member_information:'County benefits assistance, healthcare enrollment guidance and records requests. Check current appointment and walk-in availability.',confidence:'high',missing_data_flags:['program_eligibility_varies']})
];
export const places = {'All locations':null,'Yolo County':'Yolo','Solano County':'Solano','Woodland':'Yolo','Davis':'Yolo','West Sacramento':'Yolo','Winters':'Yolo','Yolo unincorporated communities':'Yolo','Benicia':'Solano','Dixon':'Solano','Fairfield':'Solano','Rio Vista':'Solano','Suisun City':'Solano','Vacaville':'Solano','Vallejo':'Solano','Travis AFB':'Solano','Cordelia':'Solano','Solano unincorporated communities':'Solano'};
export const types = ['VFW','American Legion','Marine Corps League','Veterans Beer Club','Toys for Tots','DAV','County Veterans Office','Equine program provider','Veteran remembrance program'];
export const dataset = {schema_version:'1.1',project:'Yolo Solano Veterans',research_counties:['Yolo','Solano'],last_verified_date:checked,verification_note:'Public sources reviewed; no organization has claimed or confirmed its profile. The directory is not exhaustive.',sources,records};

