import {hqLibrary} from './hq-library.mjs';
import {organizationAccessData,organizationAccessAction} from './organization-access.mjs';
import {organizationAccessPage,organizationPortalPage,organizationPhotoPresencePage} from './organization-pages.mjs';
import {getHQPrincipal,organizationProfileAction} from './organization-profile.mjs';
import {organizationPhotoRows,organizationPhotoAlbumRows,organizationPhotoPresenceRows,organizationPhotoAction,organizationPhotoCollaborationAction} from './organization-photos.mjs';
import {speakerSubmissionRows,speakerSubmissionAction} from './speaker-submissions.mjs';
import {organizationMeetingRows,organizationMeetingAction} from './organization-meetings.mjs';
import {organizationEventInvitationRows,organizationEventCollaborationAction} from './event-collaboration.mjs';
import {organizationOfficerRows,organizationOfficerAction} from './organization-officers.mjs';
import {assertPublicProfilePrivacy} from './public-privacy.mjs';
import {uploadRequestAttachment,downloadRequestAttachment,createWorkRequestWithAttachment} from './request-attachments.mjs';
import {workRequestsPage,workRequestAction} from './work-requests.mjs';
import {records} from './data.mjs';
import {escapeHtml,origin} from './site.mjs';
import {safeURL,field,choice,pacificDate,formData,getOwner,responseHTML,redirect,securityHeaders,readStaticAsset} from './storage.mjs';
const e=escapeHtml;
const opts=(values,selected)=>values.map(x=>`<option value="${e(x)}" ${x===selected?'selected':''}>${e(x.replaceAll('_',' '))}</option>`).join('');
const inp=(name,label,value='',max=500,type='text',required=false)=>`<label>${e(label)}<input name="${name}" type="${type}" value="${e(value)}" maxlength="${max}" ${required?'required':''}></label>`;
const area=(name,label,value='',max=6000)=>`<label>${e(label)}<textarea name="${name}" maxlength="${max}" rows="4">${e(value)}</textarea></label>`;
const hidden=(name,value)=>`<input type="hidden" name="${name}" value="${e(value)}">`;
const select=(name,label,values,selected)=>`<label>${e(label)}<select name="${name}">${opts(values,selected)}</select></label>`;
const orgSelect=(selected='',name='org_id')=>`<label>Organization<select name="${name}"><option value="">Choose an organization</option>${records.map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${e(r.verified_name)}</option>`).join('')}</select></label>`;
const statusLabel=s=>`<span class="label ${s==='pending'||s==='draft'?'amber':''}">${e(s.replaceAll('_',' '))}</span>`;
const dateText=s=>new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:'America/Los_Angeles'}).format(new Date(s));
function hqShell(title,content,tab='overview',message='',actor=''){
 const tabs=[['requests','Requests'],['overview','Overview'],['access','Organization access'],['tasks','Project work'],['review','Public submissions'],['events','Events'],['profiles','Profiles'],['coordination','Coordination'],['library','Ready-to-use copy']];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${e(title)} | Yolo Solano Veterans HQ</title><link rel="icon" href="/ysv-logo.png?v=logo-20260903-1" type="image/png"><link rel="stylesheet" href="/styles.css?v=officers-20260903-1"><script src="/hq.js" defer></script></head><body class="hq"><a class="skip" href="#main">Skip to content</a><header class="hq-header"><a href="/" class="hq-brand"><img class="project-logo" src="/ysv-logo.png?v=logo-20260903-1" alt="Yolo Solano Veterans" width="1254" height="1254" decoding="async"><span>Headquarters</span></a><span class="hq-private">Private workspace${actor?` � Signed in: ${e(actor)}`:''}</span><a href="${origin}" target="_blank" rel="noopener">Public website ?</a><a href="/cdn-cgi/access/logout">Sign out</a></header><div class="hq-layout"><nav class="hq-nav" aria-label="Headquarters">${tabs.map(([id,label])=>`<a href="/?tab=${id}" ${id===tab?'aria-current="page"':''}>${label}</a>`).join('')}<a href="/export.json">Download backup</a><p>Ask Chat in Requests.<br>See progress and completed work there.</p></nav><main id="main" class="hq-main"><div class="hq-title"><span class="eyebrow">YOLO &amp; SOLANO � SHARED PURPOSE</span><h1>${e(title)}</h1></div>${message?`<div class="preview-banner" role="status">${e(message)}</div>`:''}${content}<p class="small-note">Keep this workspace to organization operations. Store veteran case details, discharge papers and medical information only with an appropriate service provider. Public submissions are checked before publication.</p></main></div></body></html>`;
}
export function lockedHQ(){return responseHTML('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign-in required | Yolo Solano Veterans</title><h1>This account does not have active access.</h1><p>Sign in with the email Aaron or Sterling designated. If your assignment is awaiting setup, return after its activation is confirmed.</p><p><a href="/cdn-cgi/access/logout">Sign out to use a different email</a></p><a href="'+origin+'">Visit the public directory</a></html>',403,true);}
async function rows(db,table){return (await db.prepare(`SELECT * FROM ${table}`).all()).results;}
export async function snapshot(db){const names=['tasks','requests','events','profile_updates','coordination','audit','revisions','work_requests','work_request_messages','request_processor','work_request_attachments','organization_editors','organization_photos','organization_officers','organization_photo_albums','organization_photo_presence','speaker_submissions','speaker_submission_recipients','organization_meeting_plans','organization_meetings','organization_event_invitations'];const values=await Promise.all(names.map(name=>rows(db,name)));return Object.fromEntries(names.map((name,i)=>[name,values[i]]));}
function overview(data){const pending=data.requests.filter(x=>x.status==='pending').length,open=data.tasks.filter(x=>x.status!=='done').length,drafts=data.events.filter(x=>x.status==='draft').length;
 return `<p class="intro">A shared home for the work between meetings.</p><div class="hq-stats"><a href="/?tab=tasks"><strong>${open}</strong> open tasks</a><a href="/?tab=review"><strong>${pending}</strong> public submissions</a><a href="/?tab=events"><strong>${drafts}</strong> event drafts</a><a href="/?tab=profiles"><strong>${records.length}</strong> researched organizations</a></div><section class="panel"><h2>Start with the next useful step</h2><p>Use Requests to ask Chat for changes to the website or headquarters. Follow the work, answer a question, and see the finished result in one place.</p><div class="profile-actions"><a class="button" href="/?tab=requests">Ask Chat for a change </a><a class="button outline" href="/?tab=tasks">See project work </a></div></section><div class="two-up"><section class="panel"><h2>Meeting notes &amp; history</h2>${data.coordination.filter(x=>x.kind==='history').map(x=>`<h3>${e(x.title)}</h3><p class="preserve-lines">${e(x.notes)}</p>`).join('')||'<p>No historical notes yet.</p>'}</section><section class="panel"><h2>Recent changes</h2><ul class="activity-list">${data.audit.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,10).map(x=>`<li><strong>${e(x.action.replaceAll('_',' '))}</strong><span>${e(dateText(x.created_at))} � ${e(x.actor)}</span></li>`).join('')||'<li>The change log will appear here as you work.</li>'}</ul></section></div>`;
}
function tasksPage(data,url){const showDone=url.searchParams.get('view')==='done';return `<p class="intro">The wider project work. Chat handles routine work; use <a href="/?tab=requests">Requests</a> for anything you want done.</p><details class="panel"><summary>Add a project item</summary><form method="post" action="/action" class="edit-form">${hidden('action','task_create')}${inp('title','Task title','',180,'text',true)}<div class="two-up">${inp('category','Work area','Coordination',100)}${select('priority','Priority',['normal','high'],'normal')}</div>${area('notes','Next step or context')}<button class="button">Add project item</button></form></details><nav class="request-filters"><a href="/?tab=tasks">Chat is handling (${data.tasks.filter(t=>t.status!=='done').length})</a><a href="/?tab=tasks&view=done">Completed &amp; closed (${data.tasks.filter(t=>t.status==='done').length})</a></nav><div class="task-list">${data.tasks.filter(t=>showDone?t.status==='done':t.status!=='done').sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||Number(b.priority==='high')-Number(a.priority==='high')).map(t=>`<article class="panel"><div class="row-between"><span class="eyebrow">${e(t.category)}${t.priority==='high'?' � PRIORITY':''}</span>${statusLabel(t.status)}</div><h2>${e(t.title)}</h2><p class="preserve-lines">${e(t.notes)}</p><form class="inline-form" method="post" action="/action">${hidden('action','task_status')}${hidden('id',t.id)}${hidden('version',t.updated_at)}${select('status','Task status',['open','in_progress','done'],t.status)}<button class="button outline">Save status</button></form></article>`).join('')}</div>`;}
function publicRequestsPage(data){return `<p class="intro">Public submissions arrive here. Review the source and verify the representative before using a proposed change.</p>${data.requests.filter(r=>!data.work_requests.some(w=>w.id===r.id)).length?data.requests.filter(r=>!data.work_requests.some(w=>w.id===r.id)).sort((a,b)=>Number(b.status==='pending')-Number(a.status==='pending')||b.created_at.localeCompare(a.created_at)).map(r=>`<article class="panel"><div class="row-between"><span class="eyebrow">${e(r.kind)} � ${e(dateText(r.created_at))}</span>${statusLabel(r.status)}</div><h2>${e(r.title)}</h2><p>${e(records.find(x=>x.id===r.org_id)?.verified_name||'Organization not selected')}</p><p class="preserve-lines">${e(r.details)}</p>${r.source_url?`<p><a href="${e(r.source_url)}" target="_blank" rel="noopener noreferrer">Submitted source ?</a></p>`:''}<p class="small-note">${data.audit.some(a=>a.action==='request_create'&&a.record_id===r.id)?'Submitted while signed in as: '+e(data.audit.find(a=>a.action==='request_create'&&a.record_id===r.id).actor):'Public submission � contact identity not verified'}</p><p class="small-note">Private reply contact: ${e(r.sender_name)} � ${e(r.sender_email)}</p><div class="profile-actions"><a href="/?tab=profiles&org=${e(r.org_id||'')}">Review a profile </a><a href="/?tab=events">Prepare an event </a></div><form class="inline-form" method="post" action="/action">${hidden('action','request_status')}${hidden('id',r.id)}${hidden('version',r.updated_at)}${select('status','Review status',['pending','reviewed','archived'],r.status)}<button class="button outline">Save review status</button></form><p class="small-note">Marking a request reviewed does not publish it or grant sign-in access.</p></article>`).join(''):'<section class="empty-state panel"><h2>The review queue is clear.</h2><p>Organization corrections, event proposals and stewardship requests will appear here.</p><a href="'+origin+'/for-organizations">Open the public submission desk ?</a></section>'}`;}
function eventForm(v={}){return `<form class="edit-form" method="post" action="/action">${hidden('action','event_save')}${hidden('id',v.id||'')}${hidden('version',v.updated_at||'')}${inp('title','Event title',v.title,180,'text',true)}<div class="two-up">${orgSelect(v.organization_id)}${inp('organizer','Public organizer name',v.organizer,180,'text',true)}</div><div class="two-up">${select('kind','Event type',['Community event','Remembrance','Volunteering','Organization meeting'],v.kind||'Community event')}${select('county','County',['Yolo','Solano'],v.county||'Yolo')}</div><div class="two-up">${inp('city','City',v.city,100,'text',true)}${inp('venue','Public venue and address',v.venue,500,'text',true)}</div><label class="check"><input type="checkbox" name="date_only" value="yes" ${v.date_only?'checked':''}> Date confirmed; time to be confirmed</label>${inp('event_date','Date (when time is unconfirmed)',v.date_only?v.start_at.slice(0,10):'',10,'date')}<div class="two-up">${inp('start_at','Start - ISO date with Pacific offset',v.date_only?'':v.start_at||'',40)}${inp('end_at','End - same format, optional',v.date_only?'':v.end_at||'',40)}</div><p class="small-note">If the time is unconfirmed, select the checkbox, enter the date, and leave the start and end times blank. For timed events, use -07:00 during daylight time and -08:00 during standard time. A date must include its offset. Example: 2026-12-19T10:00:00-08:00.</p>${inp('audience','Who can attend / registration requirements',v.audience,800,'text',true)}${area('description','Public description',v.description,4000)}${select('source_kind','Where the details came from',['public_source','project_team'],v.source_kind||'public_source')}${inp('source_url','Public source, organizer website or registration link',v.source_url,2000,'url')}${inp('source_note','Project team source note',v.source_note||'',1000)}${inp('time_note','Schedule caveat',v.time_note,500)}<button class="button">Save as draft</button><p class="small-note">Saving a published event returns it to draft until reviewed again.</p></form>`;}
function eventsPage(data,url){const selected=data.events.find(x=>x.id===url.searchParams.get('event'));return `<details class="panel" ${selected?'open':''}><summary>${selected?'Edit event � returns to draft':'Prepare a new event'}</summary>${eventForm(selected?{...JSON.parse(selected.body_json),id:selected.id,updated_at:selected.updated_at}:{})}</details>${data.events.sort((a,b)=>Date.parse(JSON.parse(a.body_json).start_at)-Date.parse(JSON.parse(b.body_json).start_at)).map(row=>{const v=JSON.parse(row.body_json);return `<article class="panel"><div class="row-between"><span class="eyebrow">${e(v.kind)} � ${e(v.city)}</span>${statusLabel(row.status)}</div><h2>${e(v.title)}</h2><p>${e(v.date_only?dateText(v.start_at)+' � Time to be confirmed':v.start_at)} � ${e(v.venue)}</p><p>${e(v.description)}</p><p><strong>Audience:</strong> ${e(v.audience)}</p>${v.source_kind==='project_team'?'<p class="small-note">'+e(v.source_note||'Details supplied by the project team.')+'</p>':''}${v.source_url?'<a href="'+e(v.source_url)+'" target="_blank" rel="noopener noreferrer">'+(v.source_kind==='project_team'?'Organizer website':'Check organizer's source')+' ?</a>':''}<p><a href="/?tab=events&event=${row.id}">Edit event </a></p><form class="edit-form" method="post" action="/action">${hidden('action','event_status')}${hidden('id',row.id)}${hidden('version',row.updated_at)}${select('status','Publication status',['draft','published','archived'],row.status)}<label class="check"><input type="checkbox" name="reviewed" value="yes"> I checked the event details, date, public venue and audience before publication.</label><button class="button outline">Apply publication status</button></form></article>`;}).join('')}`;}
function profilesPage(data,url){const r=records.find(x=>x.id===url.searchParams.get('org'))||records[0],stored=data.profile_updates.find(x=>x.org_id===r.id),p=stored?JSON.parse(stored.body_json):{meeting_schedule:r.meeting_schedule,member_information:r.member_information,...r.public_contacts};return `<form method="get" class="panel inline-form">${hidden('tab','profiles')}${orgSelect(r.id,'org')}<button class="button outline">Open profile</button></form><section class="panel"><h2>${e(r.verified_name)}</h2><p><a href="${origin}/organizations/${r.id}" target="_blank" rel="noopener">View public profile ?</a></p><p class="profile-actions"><a class="button outline" href="/organization?org=${r.id}#officers">Manage officer profiles </a><a class="button outline" href="/organization?org=${r.id}#photos">Manage organization photos </a></p><p>Use general organization contacts only. Never publish member or officer rosters, personal addresses, or individual phone numbers and emails collected online. Individually authorized officer profiles can be added in the organization editor after the person agrees to public use of their profile.</p><form class="edit-form" method="post" action="/action">${hidden('action','profile_publish')}${hidden('org_id',r.id)}${hidden('version',stored?.reviewed_at||'')}${inp('meeting_schedule','Public meeting schedule',p.meeting_schedule,700)}${area('member_information','Public organization description',p.member_information,1800)}<div class="two-up">${inp('phone','Public organization phone',p.phone,80)}${inp('email','Public organization email',p.email,254,'email')}</div>${inp('website','Organization website (HTTPS)',p.website,2000,'url')}${inp('source_url','Public source supporting this correction',stored?.source_url,2000,'url',true)}<label class="check"><input type="checkbox" name="reviewed" value="yes" required> I verified these public facts against the linked source.</label><button class="button">Publish verified correction</button></form></section>`;}
function libraryPage(){return hqLibrary.map(d=>`<details class="panel" open><summary>${e(d.title)}</summary><div class="library-document">${d.body.split('\n').map(line=>line.startsWith('## ')?'<h2>'+e(line.slice(3))+'</h2>':line.startsWith('# ')?'':line?'<p>'+e(line)+'</p>':'').join('')}</div></details>`).join('');}
function coordinationPage(data){return `<p class="intro">Track the next conversation and preserve local knowledge. Nothing in this section appears on the public site.</p><details class="panel"><summary>Add a coordination note</summary><form class="edit-form" method="post" action="/action">${hidden('action','coord_create')}${select('kind','Work area',['partnership','volunteer','fundraising','history'],'partnership')}${inp('title','Title','',180,'text',true)}${area('notes','Context / progress')}${area('next_step','Next step', '',2000)}<button class="button">Save private note</button></form></details>${data.coordination.map(x=>`<article class="panel"><div class="row-between"><span class="eyebrow">${e(x.kind)}</span>${statusLabel(x.status)}</div><h2>${e(x.title)}</h2><p class="preserve-lines">${e(x.notes)}</p><form method="post" action="/action" class="edit-form">${hidden('action','coord_update')}${hidden('id',x.id)}${hidden('version',x.updated_at)}${area('next_step','Next step',x.next_step,2000)}${select('status','Status',['idea','contacted','active','closed'],x.status)}<button class="button outline">Save progress</button></form></article>`).join('')}`;}
async function mutate(db,statement,actor,action,id){const now=new Date().toISOString();const result=await db.batch([statement,db.prepare('INSERT INTO audit(id,actor,action,record_id,created_at) SELECT ?,?,?,?,? WHERE changes() > 0').bind(crypto.randomUUID(),actor,action,id,now)]);if(!result[0].meta.changes)throw new Error('This record changed in another session. Reload it before saving.');}
export async function hqAction(request,db,actor){const f=await formData(request),action=field(f,'action',50),id=field(f,'id',100)||crypto.randomUUID(),version=field(f,'version',50),now=new Date().toISOString();let q,tab;
 if(action.startsWith('org_access_'))return organizationAccessAction(f,db,actor);
 if(action.startsWith('work_'))return workRequestAction(f,db,actor);
 if(action==='task_create'){q=db.prepare('INSERT INTO tasks(id,title,category,notes,priority,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,field(f,'title',180,true),field(f,'category',100)||'Coordination',field(f,'notes',6000),choice(field(f,'priority'),['normal','high']),now,now);tab='tasks';}
 else if(action==='task_status'){q=db.prepare('UPDATE tasks SET status=?,updated_at=? WHERE id=? AND updated_at=?').bind(choice(field(f,'status'),['open','in_progress','done']),now,id,version);tab='tasks';}
 else if(action==='request_create'){const org=field(f,'org_id',100)||null;if(org&&!records.some(x=>x.id===org))throw new Error('Choose a known organization.');q=db.prepare('INSERT INTO requests(id,kind,org_id,title,details,sender_name,sender_email,source_url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,choice(field(f,'kind'),['profile','event','claim','other']),org,field(f,'title',180,true),field(f,'details',6000,true),actor,actor,safeURL(field(f,'source_url',2000)),now,now);tab='review';}
 else if(action==='request_status'){q=db.prepare('UPDATE requests SET status=?,updated_at=? WHERE id=? AND updated_at=?').bind(choice(field(f,'status'),['pending','reviewed','archived']),now,id,version);tab='review';}
 else if(action==='coord_create'){q=db.prepare('INSERT INTO coordination(id,kind,title,notes,next_step,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,choice(field(f,'kind'),['partnership','volunteer','fundraising','history']),field(f,'title',180,true),field(f,'notes',6000),field(f,'next_step',2000),now,now);tab='coordination';}
 else if(action==='coord_update'){q=db.prepare('UPDATE coordination SET status=?,next_step=?,updated_at=? WHERE id=? AND updated_at=?').bind(choice(field(f,'status'),['idea','contacted','active','closed']),field(f,'next_step',2000),now,id,version);tab='coordination';}
 else if(action==='event_save'){
  const organization_id=field(f,'org_id',100)||null;if(organization_id&&!records.some(x=>x.id===organization_id))throw new Error('Choose a known organization.');
  const stored=version?(await db.prepare('SELECT body_json FROM events WHERE id=?').bind(id).all()).results[0]:null,previous=stored?JSON.parse(stored.body_json):{};
  const dateOnlyInput=field(f,'date_only',10);if(dateOnlyInput&&dateOnlyInput!=='yes')throw new Error('Choose a valid date-only option.');
  const date_only=dateOnlyInput==='yes',event_date=field(f,'event_date',10),end_at=field(f,'end_at',40);let start_at=field(f,'start_at',40,!date_only);
  if(date_only){
   if(end_at)throw new Error('Leave the end time blank when the time is to be confirmed.');
   if(event_date){
    if(!/^\d{4}-\d{2}-\d{2}$/.test(event_date))throw new Error('Enter a valid event date.');
    if(start_at&&(!start_at.startsWith(event_date+'T00:00')||!/T00:00(?::00)?-0[78]:00$/.test(start_at)))throw new Error('Leave the start time blank when the time is to be confirmed.');
    start_at=['-08:00','-07:00'].map(offset=>event_date+'T00:00:00'+offset).find(value=>{try{return !!pacificDate(value);}catch{return false;}});
   }
   if(!start_at||!/T00:00(?::00)?-0[78]:00$/.test(start_at))throw new Error('Enter the event date and leave the time blank.');
  }
  for(const value of [start_at,end_at].filter(Boolean))pacificDate(value);
  if(end_at&&Date.parse(end_at)<=Date.parse(start_at))throw new Error('The end must follow the start.');
  const source_kind=choice(field(f,'source_kind',30)||previous.source_kind||'public_source',['public_source','project_team']),source_note=f.has('source_note')?field(f,'source_note',1000):previous.source_note||'';
  const v={id,title:field(f,'title',180,true),organization_id,organizer:field(f,'organizer',180,true),kind:choice(field(f,'kind'),['Community event','Remembrance','Volunteering','Organization meeting']),county:choice(field(f,'county'),['Yolo','Solano']),city:field(f,'city',100,true),venue:field(f,'venue',500,true),start_at,end_at:end_at||null,...(date_only?{date_only:true}:{}),audience:field(f,'audience',800,true),description:field(f,'description',4000),source_url:safeURL(field(f,'source_url',2000),source_kind!=='project_team'),source_checked:null,time_note:field(f,'time_note',500),...(source_kind==='project_team'?{source_kind,source_note}:{})};
  assertPublicProfilePrivacy({member_information:v.description+' '+v.venue,source_url:v.source_url});
  q=version?db.prepare("UPDATE events SET body_json=?,status='draft',updated_at=? WHERE id=? AND updated_at=?").bind(JSON.stringify(v),now,id,version):db.prepare("INSERT INTO events(id,body_json,status,created_at,updated_at) VALUES (?,?,'draft',?,?)").bind(id,JSON.stringify(v),now,now);tab='events';
 }
 else if(action==='event_status'){const status=choice(field(f,'status'),['draft','published','archived']);if(status==='published'&&f.get('reviewed')!=='yes')throw new Error('Confirm your source review before publishing.');q=db.prepare("UPDATE events SET status=?,body_json=CASE WHEN ?='published' THEN json_set(body_json,'$.source_checked',?) ELSE body_json END,updated_at=? WHERE id=? AND updated_at=?").bind(status,status,now.slice(0,10),now,id,version);tab='events';}
 else if(action==='profile_publish'){
  const org=field(f,'org_id',100,true);if(!records.some(x=>x.id===org))throw new Error('Unknown organization.');if(f.get('reviewed')!=='yes')throw new Error('Confirm your source review before publishing.');const source=safeURL(field(f,'source_url',2000),true),email=field(f,'email',254);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid public email.');
  const body=JSON.stringify({meeting_schedule:field(f,'meeting_schedule',700)||null,member_information:field(f,'member_information',1800,true),phone:field(f,'phone',80),email,website:safeURL(field(f,'website',2000))});
  assertPublicProfilePrivacy({...JSON.parse(body),source_url:source});
  q=version?db.prepare('UPDATE profile_updates SET body_json=?,source_url=?,reviewed_at=? WHERE org_id=? AND reviewed_at=?').bind(body,source,now,org,version):db.prepare('INSERT INTO profile_updates(org_id,body_json,source_url,reviewed_at) VALUES (?,?,?,?)').bind(org,body,source,now);await mutate(db,q,actor,action,org);return 'profiles&org='+encodeURIComponent(org);
 }else throw new Error('Unknown action.');
 await mutate(db,q,actor,action,id);return tab;
}
export async function hqFetch(request,env,ctx,assets){
 const url=new URL(request.url),head=request.method==='HEAD';
 if(['GET','HEAD'].includes(request.method)&&assets[url.pathname]){const a=assets[url.pathname];return new Response(head?null:Uint8Array.from(atob(a.base64),c=>c.charCodeAt(0)),{headers:{...securityHeaders,'Content-Type':a.type,'Cache-Control':url.pathname==='/ysv-logo.png'?'private, max-age=86400, immutable':'no-store'}});}
 const staticAsset=await readStaticAsset(request,env,url.pathname);if(staticAsset)return staticAsset;
 let principal;try{principal=await getHQPrincipal(request,env,ctx);}catch{return lockedHQ();}if(!principal)return lockedHQ();
 const actor=principal.email;
 if(!env.DB)return responseHTML(hqShell('Temporarily unavailable','<p>Headquarters storage is unavailable. Please try again later.</p>'),503,true);
 if(!principal.isAdmin){
  if(['GET','HEAD'].includes(request.method)&&url.pathname==='/'&&!url.search)return redirect('/organization');
  if(!((['/organization','/photo-presence'].includes(url.pathname)&&['GET','HEAD'].includes(request.method))||(['/organization/action','/organization/photos','/organization/officers','/organization/photo-collaboration','/organization/speakers','/organization/meetings','/organization/events'].includes(url.pathname)&&request.method==='POST')))return responseHTML('<!doctype html><html lang="en"><meta charset="utf-8"><title>Your organization access</title><h1>This page is not available to your account.</h1><p>You can manage your assigned organization pages.</p><a href="/organization">Open your organization editor</a></html>',403,true);
 }
 try{
  if(url.pathname==='/organization/photos'&&request.method==='POST')return await organizationPhotoAction(request,env,principal);
  if(url.pathname==='/organization/photo-collaboration'&&request.method==='POST')return await organizationPhotoCollaborationAction(request,env,principal);
  if(url.pathname==='/organization/officers'&&request.method==='POST')return await organizationOfficerAction(request,env,principal);
  if(url.pathname==='/organization/speakers'&&request.method==='POST')return await speakerSubmissionAction(request,env,principal,records);
  if(url.pathname==='/organization/meetings'&&request.method==='POST')return await organizationMeetingAction(request,env,principal,records);
  if(url.pathname==='/organization/events'&&request.method==='POST')return await organizationEventCollaborationAction(request,env,principal,records);
  if(url.pathname==='/organization/action'&&request.method==='POST')return redirect(await organizationProfileAction(await formData(request),env.DB,principal));
  if(url.pathname==='/photo-presence'&&['GET','HEAD'].includes(request.method)){
   const photoId=url.searchParams.get('photo')||'',photo=(await env.DB.prepare('SELECT id,org_id,alt_text FROM organization_photos WHERE id=?').bind(photoId).all()).results[0],ownerRecord=photo&&records.find(record=>record.id===photo.org_id);
   if(!photo||!ownerRecord)return responseHTML('<!doctype html><html lang="en"><meta charset="utf-8"><title>Photo not found</title><h1>This photo is no longer available.</h1><a href="/organization">Open your organization editor</a></html>',404,true);
   const eligibleRecords=(principal.isAdmin?records:records.filter(record=>principal.memberships.some(m=>m.org_id===record.id&&m.status==='active'))).filter(record=>record.id!==photo.org_id);
   return responseHTML(head?'':organizationPhotoPresencePage(photo,eligibleRecords,ownerRecord,url,principal),200,true);
  }
  if(url.pathname==='/organization'&&['GET','HEAD'].includes(request.method)){
   const allowedRecords=principal.isAdmin?records:records.filter(r=>principal.memberships.some(m=>m.org_id===r.id));
   if(url.searchParams.has('org')&&!allowedRecords.some(r=>r.id===url.searchParams.get('org')))return responseHTML('<!doctype html><html lang="en"><meta charset="utf-8"><title>Organization access</title><h1>You do not manage this organization.</h1><a href="/organization">Return to your organization editor</a></html>',403,true);
   const ids=allowedRecords.map(r=>r.id);
   const updates=ids.length?(await env.DB.prepare('SELECT org_id,body_json,source_url,reviewed_at FROM profile_updates WHERE org_id IN ('+ids.map(()=>'?').join(',')+')').bind(...ids).all()).results:[];
   const photos=await organizationPhotoRows(env.DB,ids);
   const albums=await organizationPhotoAlbumRows(env.DB,ids);
   const presences=await organizationPhotoPresenceRows(env.DB,photos.map(photo=>photo.id));
   for(const photo of photos)photo.presences=presences.filter(row=>row.photo_id===photo.id);
   const officers=await organizationOfficerRows(env.DB,ids);
   const speakerRows=await speakerSubmissionRows(env.DB,ids);
   const meetingData=await organizationMeetingRows(env.DB,ids);
   const eventInvitationRows=await organizationEventInvitationRows(env.DB,ids);
   return responseHTML(head?'':organizationPortalPage(allowedRecords,updates,principal.memberships,url,principal.isAdmin?{email:actor,isAdmin:true}:actor,photos,officers,albums,records,speakerRows,meetingData,eventInvitationRows),200,true);
  }
  if(request.method==='POST'&&url.pathname==='/requests')return await createWorkRequestWithAttachment(request,env,actor);
  if(request.method==='POST'&&url.pathname==='/attachments')return await uploadRequestAttachment(request,env,actor);
  if(['GET','HEAD'].includes(request.method)&&url.pathname.startsWith('/attachments/'))return await downloadRequestAttachment(request,env,url.pathname.slice('/attachments/'.length));
  if(request.method==='POST'&&url.pathname==='/action'){const tab=await hqAction(request,env.DB,actor);return redirect('/?tab='+tab+'&saved=1');}
  if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:{...securityHeaders,Allow:'GET, HEAD','Cache-Control':'no-store'}});
  if(url.pathname==='/request-state'){const state=await env.DB.prepare("SELECT (SELECT count(*) FROM work_requests) AS count,(SELECT COALESCE(sum(version),0) FROM work_requests) AS version,last_checked_at,mode FROM request_processor WHERE id='main'").all();return new Response(head?null:JSON.stringify(state.results[0]),{headers:{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store'}});}
  if(!['/','/export.json'].includes(url.pathname))return responseHTML(hqShell('Page not found','<a href="/">Return to headquarters</a>'),404,true);
  const data=await snapshot(env.DB);
  if(url.pathname==='/export.json')return new Response(head?null:JSON.stringify({project:'Yolo Solano Veterans',exported_at:new Date().toISOString(),schema_version:11,...data},null,2),{headers:{...securityHeaders,'Content-Type':'application/json','Content-Disposition':'attachment; filename="veterans-hq-backup.json"','Cache-Control':'no-store','X-Robots-Tag':'noindex'}});
  const tab=url.searchParams.get('tab')||'requests',pages={overview:['Your headquarters',()=>overview(data)],tasks:['Project work',()=>tasksPage(data,url)],requests:['Requests',()=>workRequestsPage(data,url,actor)],review:['Public submissions',()=>publicRequestsPage(data)],events:['Shared calendar',()=>eventsPage(data,url)],profiles:['Organization profiles',()=>profilesPage(data,url)],coordination:['People & shared projects',()=>coordinationPage(data)],library:['Ready-to-use copy & working defaults',()=>libraryPage()]};
  pages.access=['Organization access',()=>organizationAccessPage(data.organization_editors,records)];
  const page=pages[tab]||pages.overview;return responseHTML(head?'':hqShell(page[0],page[1](),tab,url.searchParams.has('saved')?'Saved. Your change is recorded in the activity log.':'',actor),200,true);
 }catch(err){const userError=err instanceof Error&& !/D1_|SQLITE|constraint|database/i.test(err.message);const message=userError?err.message:'The record could not be saved. Reload it and try again; your existing record remains unchanged.';
  if(!principal.isAdmin)return responseHTML('<!doctype html><html lang="en"><meta charset="utf-8"><title>Unable to save organization</title><h1>Unable to save</h1><p>'+e(message)+'</p><a href="/organization">Return to your organization editor</a></html>',400,true);
  return responseHTML(hqShell('Unable to save',`<section class="panel"><p>${e(message)}</p><a href="/">Return to headquarters </a></section>`),400,true);}
}

