import {shell,escapeHtml} from './site.mjs';

// Historical schedules are intentionally kept outside the upcoming event feed.
export const memorialServices=[
 {city:'Davis',county:'Yolo',title:'Davis Cemetery Memorial Day Program',schedule:'May 25, 2026 · musical prelude 9:30 a.m.; ceremony 10 a.m.',venue:'Davis Cemetery, 820 Pole Line Road, Davis',notes:'The cemetery’s 2026 program is the latest verified edition. The 2027 ceremony schedule has not been announced in the sources reviewed.',sources:[['Davis Cemetery program','https://daviscemetery.org/memorial-day-ceremony/']]},
 {city:'Davis',county:'Yolo',title:'UC Davis Gold Star Aggies Ceremony',schedule:'May 21, 2026 · 12:15–12:45 p.m.',venue:'Memorial Union North Courtyard, UC Davis',notes:'The campus remembrance took place before the Monday holiday. The 2027 ceremony schedule has not been verified.',sources:[['UC Davis event announcement','https://memorialunion.ucdavis.edu/events/2026-memorial-day-ceremony']]},
 {city:'Woodland',county:'Yolo',title:'Woodland Cemetery remembrance',schedule:null,venue:'Woodland Cemetery, 800 West Street, Woodland',notes:'Yolo American Legion Post 77 organized remembrance here in 2023. A current ceremony date and time have not been verified. Contact the cemetery at 530-661-2000 for the next program.',sources:[['City cemetery information','https://www.cityofwoodland.gov/257/Cemetery'],['American Legion’s 2023 report','https://www.legion.org/information-center/news/honor/2023/june/memorial-day-with-the-american-legion-family']]},
 {city:'Winters',county:'Yolo',title:'Winters Cemetery Memorial Day Service',schedule:'May 25, 2026 · 1:30 p.m.',venue:'Winters Cemetery, 415 Cemetery Drive, Winters',notes:'The cemetery also held volunteer flag placement on May 22, 2026 at 9 a.m. These are past schedules; 2027 details have not been verified.',sources:[['2026 cemetery service','https://www.winterscemetery.org/2026-05-25-memorial-day-service'],['2026 flag placement','https://www.winterscemetery.org/2026-05-22-memorial-day-event']]},
 {city:'Dixon',county:'Solano',title:'Sacramento Valley National Cemetery',schedule:'May 23, 2026 · 9 a.m.',venue:'Sacramento Valley National Cemetery, 5810 Midway Road, Dixon',notes:'The VA scheduled this 2026 ceremony on Saturday, two days before Memorial Day. Do not assume it will take place on the Monday holiday in 2027.',sources:[['VA’s 2026 Memorial Day ceremonies','https://www.cem.va.gov/volunteer/Memorial-Day.asp']]},
 {city:'Benicia',county:'Solano',title:'Benicia Arsenal Post Cemetery',schedule:'May 25, 2026 · 10 a.m.',venue:'Benicia Arsenal Post Cemetery, Benicia',notes:'The VA’s 2026 ceremony list confirms this past date and time. The 2027 schedule has not been verified.',sources:[['VA’s 2026 Memorial Day ceremonies','https://www.cem.va.gov/volunteer/Memorial-Day.asp']]},
 {city:'Vallejo',county:'Solano',title:'Mare Island Naval Cemetery',schedule:'May 25, 2026 · 9 a.m.',venue:'Mare Island Naval Cemetery, 167 O’Hara Court, Vallejo',notes:'The VA’s 2026 ceremony list confirms this past date and time. The 2027 schedule has not been verified.',sources:[['VA’s 2026 Memorial Day ceremonies','https://www.cem.va.gov/volunteer/Memorial-Day.asp'],['VA cemetery information','https://www.cem.va.gov/cems/nchp/MareIslandNaval.asp']]},
 {city:'Vallejo',county:'Solano',title:'Vallejo Warriors’ Memorial',schedule:'May 25, 2026 · 11–11:50 a.m.',venue:'Martin Luther King Jr. Park behind City Hall, 3 Capitol Street, Vallejo',notes:'This past schedule was reported by the Vallejo Sun; direct organizer confirmation was not found. The 2027 program has not been verified.',sources:[['Vallejo Sun’s May 20, 2026 event listing','https://www.vallejosun.com/upcoming-vallejo-events-punk-rock-festival-at-the-odd-fellows-hall/']]},
 {city:'Vacaville',county:'Solano',title:'Vacaville-Elmira Cemetery',schedule:'May 26, 2025 · 11 a.m.',venue:'Vacaville-Elmira Cemetery, 522 Elmira Road, Vacaville',notes:'KCRA reported this 2025 ceremony. A 2026 or 2027 ceremony schedule has not been verified. Contact the cemetery at 707-448-7206 for the next program.',sources:[['KCRA’s 2025 ceremony listing','https://www.kcra.com/article/sacramento-memorial-day-ceremonies-2025/64881902'],['Cemetery district','https://www.vecd.us/']]},
 {city:'Rio Vista',county:'Solano',title:'American Legion Post 178 remembrance',schedule:null,venue:'In front of Rio Vista City Hall — previous annual tradition',notes:'A November 2025 Congressional tribute records an annual Memorial Day ceremony here and grave flag placement. It gives no date or time for the next event. Contact Post 178 at 707-374-6554.',sources:[['2025 Congressional tribute','https://www.congress.gov/119/crec/2025/11/10/171/190/CREC-2025-11-10-pt1-PgE1052-4.pdf'],['American Legion Post 178','https://post178rvca.org/']]},
 {city:'Fairfield / Suisun City',county:'Solano',title:'Local veterans’ remembrance',schedule:null,venue:'Next venue to be confirmed',notes:'Reams American Legion Post 182 and VFW were named in an official 2017 announcement for remembrance at the Old Solano County Courthouse in Fairfield. That is historical context only. Contact Post 182 at 707-429-3110 for the current program.',sources:[['Reams American Legion Post 182','https://reamspost182.org/'],['Historical 2017 Assembly announcement','https://wilson.asmdc.org/sites/a11.asmdc.org/files/e_alert/20170505AD11EAlert_1636.htm']]}
];

export function memorialDayPage(url){
 const mh=escapeHtml,county=['Yolo','Solano'].includes(url.searchParams.get('county'))?url.searchParams.get('county'):'';
 const selected=memorialServices.filter(v=>!county||v.county===county);
 return shell('Memorial Day services | Yolo Solano Veterans','A city-by-city guide to Memorial Day remembrance in Yolo and Solano counties, with verified past schedules and links to local organizers.',`<section class="wrap about-page"><p><a class="back" href="/events">← Community events</a></p><span class="eyebrow">REMEMBERING TOGETHER</span><h1>Memorial Day.<br><em>Across our communities.</em></h1><p class="intro">Find local remembrance services and the people organizing them.</p><section class="panel"><span class="label amber">Planning for 2027</span><h2>Monday, May 31, 2027 is Memorial Day.</h2><p>Local ceremonies can take place on a different day. The next ceremony schedules have not been verified in our September 2, 2026 research. Below are the latest schedules we could confirm, clearly marked as past events, and local contacts for programs awaiting details.</p><a href="https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/#url=2027" target="_blank" rel="noopener noreferrer">Official holiday calendar ↗</a></section><form class="panel inline-form" method="get"><label for="memorial-county">Explore by county</label><select id="memorial-county" name="county"><option value="">Yolo &amp; Solano</option><option value="Yolo" ${county==='Yolo'?'selected':''}>Yolo</option><option value="Solano" ${county==='Solano'?'selected':''}>Solano</option></select><button class="button">Show services</button></form><p class="results-note">All times are Pacific. Past schedules are reference only and are not added to the upcoming calendar.</p><div class="two-up">${selected.map(v=>`<article class="panel"><div class="row-between"><span class="eyebrow">${mh(v.city)} · ${mh(v.county)} County</span><span class="label ${v.schedule?'':'amber'}">${v.schedule?'Past schedule':'Schedule awaiting details'}</span></div><h2>${mh(v.title)}</h2><p class="event-time">${mh(v.schedule||'Next date and time to be confirmed')}</p><p>${mh(v.venue)}</p><p>${mh(v.notes)}</p><ul>${v.sources.map(([title,href])=>`<li><a href="${mh(href)}" target="_blank" rel="noopener noreferrer">${mh(title)} ↗</a></li>`).join('')}</ul></article>`).join('')}</div><section class="panel"><h2>More communities</h2><p>A current ceremony schedule has not yet been verified for West Sacramento, Esparto/Capay, Knights Landing, Cordelia or Travis AFB. This does not mean those communities have no observance.</p><p>Have an organizer’s announcement or flyer? Share it so the date, venue and public attendance details can be added.</p><a class="button outline" href="/for-organizations?kind=event">Share a ceremony →</a></section></section>`,{path:'/memorial-day'});
}
