import {escapeHtml,origin} from './site.mjs';
import {speakerInbox} from './speaker-submissions.mjs';
import {organizationMeetingPlanner} from './organization-meetings.mjs';
import {organizationEventCollaboration} from './event-collaboration.mjs';

const organizationPageEscape=escapeHtml;
const organizationPageHidden=(name,value)=>'<input type="hidden" name="'+organizationPageEscape(name)+'" value="'+organizationPageEscape(value)+'">';
const organizationPageInput=(name,label,value='',max=500,type='text',required=false)=>'<label>'+organizationPageEscape(label)+'<input name="'+organizationPageEscape(name)+'" type="'+type+'" value="'+organizationPageEscape(value)+'" maxlength="'+max+'" '+(required?'required':'')+'></label>';
const organizationPageArea=(name,label,value='',max=1800,required=false)=>'<label>'+organizationPageEscape(label)+'<textarea name="'+organizationPageEscape(name)+'" maxlength="'+max+'" rows="5" '+(required?'required':'')+'>'+organizationPageEscape(value)+'</textarea></label>';
const organizationPageWhen=value=>{
 if(!value||!Number.isFinite(Date.parse(value)))return '';
 return new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:'America/Los_Angeles'}).format(new Date(value));
};
const organizationPageName=(records,id)=>records.find(r=>r.id===id)?.verified_name||'Organization no longer listed';

// This fragment is rendered only inside the administrator's private HQ shell.
export function organizationAccessPage(memberships,records){
 const esc=organizationPageEscape,ordered=[...memberships].sort((a,b)=>Number(a.status==='revoked')-Number(b.status==='revoked')||organizationPageName(records,a.org_id).localeCompare(organizationPageName(records,b.org_id))||a.email.localeCompare(b.email));
 const counts={active:memberships.filter(m=>m.status==='active').length,pending:memberships.filter(m=>m.status==='pending').length};
 const orgOptions=[...records].sort((a,b)=>a.verified_name.localeCompare(b.verified_name)).map(r=>'<option value="'+esc(r.id)+'">'+esc(r.verified_name)+'</option>').join('');
 return '<p class="intro">Give a designated representative access to their organization’s public page. Each person signs in with their own email, and their published changes are recorded.</p>'+
 '<section class="panel request-compose"><span class="eyebrow">ORGANIZATION REPRESENTATIVES</span><h2>Add a representative</h2><p>You are designating this person to manage this organization. Chat activates their sign-in and records the result in Requests.</p>'+
 '<form class="edit-form" method="post" action="/action">'+organizationPageHidden('action','org_access_grant')+
 '<div class="two-up">'+organizationPageInput('email','Representative’s sign-in email','',254,'email',true)+organizationPageInput('display_name','Representative’s name (optional)','',120)+'</div>'+
 '<label>Organization<select name="org_id" required><option value="">Choose an organization</option>'+orgOptions+'</select></label>'+
 '<p class="small-note">Access is limited to the organization selected here. To authorize the same person for another organization, add that assignment separately.</p>'+
 '<button class="button">Designate representative →</button></form></section>'+
 '<div class="section-heading"><div><span class="eyebrow">SHARED RESPONSIBILITY</span><h2>Representative access</h2></div><span class="result-count">'+counts.active+' active · '+counts.pending+' awaiting sign-in setup</span></div>'+
 '<p class="results-note">Representatives use <a href="/organization">the organization editor</a>. They can publish public contact, meeting and description updates for their assigned organizations.</p>'+
 (ordered.length?ordered.map(m=>{
  const status={pending:'Awaiting sign-in setup',active:'Active',revoked:'Revoked'}[m.status]||'Access unavailable';
  const date=organizationPageWhen(m.updated_at),known=records.some(r=>r.id===m.org_id);
  const action=m.status==='revoked'?
   (known?'<form class="inline-form" method="post" action="/action">'+organizationPageHidden('action','org_access_grant')+organizationPageHidden('id',m.id)+organizationPageHidden('version',m.version)+organizationPageHidden('email',m.email)+organizationPageHidden('org_id',m.org_id)+organizationPageHidden('display_name',m.display_name||'')+'<button class="button outline">Restore representative access</button></form>':''):
   '<form class="inline-form" method="post" action="/action">'+organizationPageHidden('action','org_access_revoke')+organizationPageHidden('id',m.id)+organizationPageHidden('version',m.version)+'<button class="button outline">Revoke organization access</button></form>';
  return '<article class="panel"><div class="row-between"><span class="eyebrow">DESIGNATED REPRESENTATIVE</span><span class="label '+(m.status==='pending'?'amber':'')+'">'+esc(status)+'</span></div>'+
   '<h2>'+esc(organizationPageName(records,m.org_id))+'</h2><p><strong>'+esc(m.display_name||m.email)+'</strong>'+(m.display_name?'<br>'+esc(m.email):'')+'</p>'+
   (m.status==='pending'?'<p>Chat is preparing this person’s sign-in. The activation result will appear in <a href="/?tab=requests">Requests</a>.</p>':m.status==='revoked'?'<p>This person’s access to this organization has been revoked. Restoring access requests a new sign-in activation.</p>':'<p>This person can update and publish this organization’s public page.</p>')+
   (date?'<p class="small-note">Last changed '+esc(date)+'.</p>':'')+action+'</article>';
 }).join(''):'<section class="panel empty-state"><h2>No representatives designated yet.</h2><p>Add a representative above to give an organization its own editor.</p></section>');
}

// The actor comes from verified server-side identity, never from form or query values.
// Administrators may pass {email, isAdmin:true} after the HQ owner check succeeds.
function organizationPortalPageBase(records,updates,memberships,url,actor,photos=[],officers=[],albums=[],allRecords=records,speakerRows=[]){
 const esc=organizationPageEscape,email=String(typeof actor==='string'?actor:actor?.email||'').trim().toLowerCase();
 const admin=!!email&&typeof actor==='object'&&actor?.isAdmin===true;
 const assigned=new Set(memberships.filter(m=>m.status==='active'&&String(m.email||'').trim().toLowerCase()===email).map(m=>m.org_id));
 const allowed=records.filter(r=>email&&(admin||assigned.has(r.id))).sort((a,b)=>a.verified_name.localeCompare(b.verified_name));
 const selected=allowed.find(r=>r.id===url.searchParams.get('org'))||allowed[0];
 const publicLink=selected?origin+'/organizations/'+encodeURIComponent(selected.id):null;
 let content;
 if(!selected){
  content='<section class="panel"><h2>Your organization access is not active yet.</h2><p>Use the email that Aaron or Sterling designated for your organization. If sign-in setup is still pending, return after they confirm that it is active.</p><p class="small-note">Signed in as '+esc(email)+'.</p></section>';
 }else{
  const stored=updates.find(u=>u.org_id===selected.id);let published=null;
  if(stored){try{published=JSON.parse(stored.body_json);}catch{published=null;}}
  const values=published||{meeting_schedule:selected.meeting_schedule,member_information:selected.member_information,...selected.public_contacts};
  const options=allowed.map(r=>'<option value="'+esc(r.id)+'" '+(r.id===selected.id?'selected':'')+'>'+esc(r.verified_name)+'</option>').join('');
  content=(url.searchParams.has('saved')?'<div class="preview-banner" role="status"><strong>Your changes are published.</strong><span>They are saved on the public website and recorded under your sign-in email. <a href="'+esc(publicLink)+'" target="_blank" rel="noopener noreferrer">View your organization’s page ↗</a></span></div>':'')+
   '<p class="intro">Keep your organization’s public page current. Reviewed changes are published immediately when you choose Publish below.</p>'+
   '<form class="panel inline-form" method="get" action="/organization"><label for="organization-selector">Your organization</label><select id="organization-selector" name="org">'+options+'</select><button class="button outline">Open organization</button></form>'+
   '<section class="panel"><div class="row-between"><span class="eyebrow">YOUR ORGANIZATION’S PUBLIC PAGE</span><a href="'+esc(publicLink)+'" target="_blank" rel="noopener noreferrer">View public page ↗</a></div><h2>'+esc(selected.verified_name)+'</h2>'+
   '<p>Update the meeting schedule, public description and contact information below. These fields appear on your organization’s public page.</p>'+
   '<form class="edit-form" method="post" action="/organization/action">'+organizationPageHidden('action','organization_profile_publish')+organizationPageHidden('org_id',selected.id)+organizationPageHidden('version',stored?.reviewed_at||'')+
   organizationPageInput('meeting_schedule','Public meeting schedule',values.meeting_schedule||'',700)+
   organizationPageArea('member_information','Public organization description',values.member_information||'',1800,true)+
   '<div class="two-up">'+organizationPageInput('phone','Public organization phone',values.phone||'',80,'tel')+organizationPageInput('email','Public organization email',values.email||'',254,'email')+'</div>'+
   organizationPageInput('website','Organization website (HTTPS)',values.website||'',2000,'url')+
   organizationPageInput('source_url','Organization website or public source (HTTPS)',stored?.source_url||selected.public_contacts?.website||'',2000,'url',true)+
   '<p class="small-note">Link to the organization’s website, public notice or other public source supporting these details. Website and source links must begin with https://.</p>'+
   '<label class="check"><input type="checkbox" name="reviewed" value="yes" required> I am authorized to publish these public organization details, and I have checked them against the linked source.</label>'+
   '<button class="button">Publish organization updates →</button><p class="small-note">Use general organization contact channels only. Do not publish member or officer rosters, personal addresses, personal phone numbers or personal emails found online. Do not include veteran case details, discharge documents or medical information.</p></form></section>'+organizationOfficerEditor(selected.id,officers.filter(officer=>officer.org_id===selected.id),photos.filter(photo=>photo.org_id===selected.id),url.searchParams.has('officersaved'))+organizationPhotoEditor(selected.id,photos.filter(photo=>photo.org_id===selected.id),url.searchParams.has('photosaved'),albums.filter(album=>album.org_id===selected.id),allRecords);
 }
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#102b52"><title>Organization editor | Yolo Solano Veterans</title><link rel="icon" href="/ysv-logo.png?v=logo-20260903-1" type="image/png"><link rel="stylesheet" href="/styles.css?v=officers-20260903-1"></head><body class="hq"><a class="skip" href="#main">Skip to content</a><header class="hq-header"><span class="hq-brand"><img class="project-logo" src="/ysv-logo.png?v=logo-20260903-1" alt="Yolo Solano Veterans" width="1254" height="1254" decoding="async"><span>Organization editor</span></span><span class="hq-private">Signed in: '+esc(email)+'</span>'+(publicLink?'<a href="'+esc(publicLink)+'" target="_blank" rel="noopener noreferrer">Public organization page ↗</a>':'')+'<a href="/cdn-cgi/access/logout">Sign out</a></header><main id="main" class="wrap workspace-page"><span class="eyebrow">LOCAL KNOWLEDGE · UP TO DATE</span><h1>Your organization.</h1>'+content+'</main></body></html>';
}

export function organizationPortalPage(records,updates,memberships,url,actor,photos=[],officers=[],albums=[],allRecords=records,speakerRows=[],meetingData={plans:[],meetings:[]},eventInvitationRows=[]){
 const email=String(typeof actor==='string'?actor:actor?.email||'').trim().toLowerCase(),admin=!!email&&typeof actor==='object'&&actor?.isAdmin===true,assigned=new Set(memberships.filter(m=>m.status==='active'&&String(m.email||'').trim().toLowerCase()===email).map(m=>m.org_id)),allowed=records.filter(r=>email&&(admin||assigned.has(r.id))).sort((a,b)=>a.verified_name.localeCompare(b.verified_name)),selected=allowed.find(r=>r.id===url.searchParams.get('org'))||allowed[0];
 const html=organizationPortalPageBase(records,updates,memberships,url,actor,photos,officers,albums,allRecords,speakerRows);
 return selected?html.replace('</main>',organizationEventCollaboration(selected.id,allRecords,eventInvitationRows,url.searchParams.has('eventshared'))+organizationMeetingPlanner(selected.id,meetingData,url)+speakerInbox(selected.id,speakerRows,url.searchParams.has('speakersaved'))+'</main>'):html;
}

function organizationOfficerEditor(orgId,officers,photos,saved){
 const esc=organizationPageEscape,hidden=organizationPageHidden,input=organizationPageInput,area=organizationPageArea,context=hidden('org_id',orgId);
 const photoOptions=selected=>'<option value="">No photo</option>'+photos.map((photo,index)=>'<option value="'+esc(photo.id)+'" '+(photo.id===selected?'selected':'')+'>'+esc((photo.caption||photo.alt_text||('Organization photo '+(index+1))).slice(0,100))+'</option>').join('');
 const fields=officer=>input('public_name','Officer public name',officer?.public_name||'',120,'text',true)+input('title','Current officer title',officer?.title||'',160,'text',true)+area('bio','Short public bio',officer?.bio||'',1200,true)+'<label>Optional approved photo<select name="photo_id">'+photoOptions(officer?.photo_id||'')+'</select></label><p class="small-note">Choose a photo already published in the Photos section. If needed, add the approved portrait below first, then return here to select it.</p>';
 const consent='<label class="check"><input type="checkbox" name="consent" value="yes" required> I confirm this person agreed to public display of their name, title, bio and selected photo. I have not included personal contact details, a home address, membership information, veteran case details or a roster.</label>';
 return '<section id="officers" class="organization-officers panel"><span class="eyebrow">VOLUNTARY PUBLIC PROFILES</span><h2>Officers</h2>'+(saved?'<p class="preview-banner" role="status">Your officer profile changes are published.</p>':'')+'<p>Add individual profiles with the officer\'s permission. These profiles appear immediately on the organization\'s website page and are not presented as a complete officer roster.</p>'+
  (officers.length<20?'<details class="panel" '+(!officers.length?'open':'')+'><summary>Add an officer profile</summary><form class="edit-form" method="post" action="/organization/officers">'+hidden('action','officer_add')+context+fields()+consent+'<button class="button">Publish officer profile →</button></form></details>':'<p>This organization has 20 officer profiles. Remove one before adding another.</p>')+
  '<div class="officer-grid">'+officers.map(officer=>'<article class="officer-card">'+(officer.selected_photo_id?'<img src="'+esc(officer.photo_image_url||origin+'/organization-photos/'+encodeURIComponent(officer.selected_photo_id))+'" alt="'+esc(officer.photo_alt_text||('Portrait of '+officer.public_name))+'" loading="lazy" decoding="async" referrerpolicy="no-referrer">':'<div class="officer-placeholder" aria-hidden="true">'+esc(officer.public_name.slice(0,1).toUpperCase())+'</div>')+'<div><span class="eyebrow">'+esc(officer.title)+'</span><h3>'+esc(officer.public_name)+'</h3><p class="preserve-lines">'+esc(officer.bio)+'</p></div><details><summary>Edit profile</summary><form class="edit-form" method="post" action="/organization/officers">'+hidden('action','officer_edit')+context+hidden('id',officer.id)+hidden('version',officer.version)+fields(officer)+consent+'<button class="button outline">Publish officer changes</button></form></details><details><summary>Remove profile</summary><p>The profile will be removed from the public page. Private change history remains in the headquarters backup.</p><form method="post" action="/organization/officers">'+hidden('action','officer_remove')+context+hidden('id',officer.id)+hidden('version',officer.version)+'<button class="button outline">Remove officer profile</button></form></details></article>').join('')+'</div></section>';
}

function organizationPhotoEditor(orgId,photos,saved,albums,allRecords){
 const esc=organizationPageEscape,hidden=organizationPageHidden,input=organizationPageInput,area=organizationPageArea;
 const context=hidden('org_id',orgId),otherRecords=allRecords.filter(record=>record.id!==orgId).sort((a,b)=>a.verified_name.localeCompare(b.verified_name));
 const albumOptions=selected=>'<option value="">No album</option>'+albums.map(album=>'<option value="'+esc(album.id)+'" '+(album.id===selected?'selected':'')+'>'+esc(album.name)+'</option>').join('');
 const presenceFields=photo=>{const approved=new Set((photo?.presences||[]).filter(row=>row.status==='approved').map(row=>row.org_id));return '<fieldset class="organization-checkboxes"><legend>Other organizations in this photo (optional)</legend><p class="small-note">Your organization is included automatically. Select other organizations that were present.</p>'+otherRecords.map(record=>'<label class="check"><input type="checkbox" name="present_org_ids" value="'+esc(record.id)+'" '+(approved.has(record.id)?'checked':'')+'> '+esc(record.verified_name)+'</label>').join('')+'</fieldset>';};
 const fields=photo=>'<label>Album<select name="album_id">'+albumOptions(photo?.album_id||'')+'</select></label>'+input('caption','Short description under the photo (optional)',photo?.caption||'',500)+input('alt_text','Describe what is in the photo',photo?.alt_text||'',300,'text',true)+input('credit','Photo credit (optional)',photo?.credit||'',200)+input('source_url','Original public source (optional)',photo?.source_url||'',2000,'url')+presenceFields(photo);
 const confirmation='<label class="check"><input type="checkbox" name="rights" value="yes" required> I have permission to publish this photo and the people pictured have agreed to its public use where needed. It contains no rosters, private contact details, documents or sensitive veteran information.</label>';
 const albumManager='<section id="photo-albums" class="photo-album-manager"><span class="eyebrow">ORGANIZE YOUR PHOTOS</span><h3>Albums</h3><p>Create albums with a short introduction. Removing an album keeps its photos and moves them back to Photos.</p>'+
  (albums.length<20?'<details class="panel"><summary>Create an album</summary><form class="edit-form" method="post" action="/organization/photo-collaboration">'+hidden('action','album_add')+context+input('name','Album name','',100,'text',true)+area('description','Short album description','',500)+'<button class="button">Create album</button></form></details>':'<p>This organization has 20 albums.</p>')+
  '<div class="album-manager-grid">'+albums.map(album=>'<article class="panel"><h4>'+esc(album.name)+'</h4>'+(album.description?'<p>'+esc(album.description)+'</p>':'')+'<details><summary>Edit album</summary><form class="edit-form" method="post" action="/organization/photo-collaboration">'+hidden('action','album_edit')+context+hidden('id',album.id)+hidden('version',album.version)+input('name','Album name',album.name,100,'text',true)+area('description','Short album description',album.description||'',500)+'<button class="button outline">Save album</button></form></details><form method="post" action="/organization/photo-collaboration">'+hidden('action','album_remove')+context+hidden('id',album.id)+hidden('version',album.version)+'<button class="button outline">Remove album</button></form></article>').join('')+'</div></section>';
 return '<section id="photos" class="organization-photos panel"><span class="eyebrow">SHARE YOUR ORGANIZATION</span><h2>Photos</h2>'+(saved?'<p class="preview-banner" role="status">Your photo and album changes are published.</p>':'')+'<p>Add photos of your public venue, activities or community. Photos appear immediately on your organization\'s website page. You can keep up to 12 photos, organize them into albums and identify collaborating organizations.</p>'+albumManager+
  (photos.length<12?'<details class="panel" '+(!photos.length?'open':'')+'><summary>Add a photo</summary><form class="edit-form" method="post" action="/organization/photos" enctype="multipart/form-data">'+hidden('action','photo_upload')+context+'<label>Choose a photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required></label><p class="small-note">JPG, PNG or WebP · up to 5 MB. Embedded location and camera notes are removed before publication.</p>'+fields()+confirmation+'<button class="button">Publish photo →</button></form></details>':'<p>You have 12 photos. Remove one below before adding another.</p>')+
  '<div class="photo-grid">'+photos.map(photo=>{const approved=(photo.presences||[]).filter(row=>row.status==='approved').map(row=>organizationPageName(allRecords,row.org_id)),pending=(photo.presences||[]).filter(row=>row.status==='pending');return '<article class="photo-card"><img src="'+esc(photo.image_url||origin+'/organization-photos/'+encodeURIComponent(photo.id))+'" alt="'+esc(photo.alt_text)+'" loading="lazy" decoding="async" referrerpolicy="no-referrer"><p class="photo-present"><strong>Organizations:</strong> '+esc(approved.join(', ')||organizationPageName(allRecords,orgId))+'</p>'+(photo.caption?'<p>'+esc(photo.caption)+'</p>':'')+(photo.credit?'<p class="small-note">'+esc(photo.credit)+'</p>':'')+(pending.length?'<div class="photo-presence-requests"><strong>Requests to join this photo</strong>'+pending.map(row=>'<div class="row-between"><span>'+esc(organizationPageName(allRecords,row.org_id))+'</span><span><form class="inline-form" method="post" action="/organization/photo-collaboration">'+hidden('action','photo_presence_approve')+context+hidden('id',row.id)+hidden('version',row.version)+'<button class="button outline">Approve</button></form><form class="inline-form" method="post" action="/organization/photo-collaboration">'+hidden('action','photo_presence_reject')+context+hidden('id',row.id)+hidden('version',row.version)+'<button class="button outline">Decline</button></form></span></div>').join('')+'</div>':'')+'<details><summary>Edit photo details</summary><form class="edit-form" method="post" action="/organization/photos">'+hidden('action','photo_edit')+context+hidden('id',photo.id)+hidden('version',photo.version)+fields(photo)+confirmation+'<button class="button outline">Publish photo details</button></form></details><details><summary>Remove this photo</summary><p>The photo will be removed from the public page.</p><form method="post" action="/organization/photos">'+hidden('action','photo_remove')+context+hidden('id',photo.id)+hidden('version',photo.version)+'<button class="button outline">Remove photo from website</button></form></details></article>';}).join('')+'</div></section>';
}

export function organizationPhotoPresencePage(photo,eligibleRecords,ownerRecord,url,actor){
 const esc=organizationPageEscape,hidden=organizationPageHidden,saved=url.searchParams.has('saved');
 const options=eligibleRecords.map(record=>'<option value="'+esc(record.id)+'">'+esc(record.verified_name)+'</option>').join('');
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Add your organization | Yolo Solano Veterans</title><link rel="stylesheet" href="/styles.css?v=albums-20260904-1"></head><body class="hq"><header class="hq-header"><span class="hq-brand">Photo collaboration</span><span class="hq-private">Signed in: '+esc(actor.email)+'</span><a href="/organization">Organization editor</a></header><main class="wrap workspace-page"><a class="back" href="'+esc(origin+'/organizations/'+ownerRecord.id+'#photos')+'">Back to photo</a><section class="panel"><span class="eyebrow">COLLABORATION</span><h1>Add your organization</h1>'+(saved?'<p class="preview-banner" role="status">Your request was sent to '+esc(ownerRecord.verified_name)+' for approval.</p>':'')+'<img class="presence-photo-preview" src="'+esc(origin+'/organization-photos/'+photo.id)+'" alt="'+esc(photo.alt_text)+'"><p>This photo belongs to <strong>'+esc(ownerRecord.verified_name)+'</strong>. Choose one of the organizations you manage. The photo owner will review your request before the organization name appears publicly.</p>'+(options?'<form class="edit-form" method="post" action="/organization/photo-collaboration">'+hidden('action','photo_presence_request')+hidden('photo_id',photo.id)+'<label>Your organization<select name="org_id" required>'+options+'</select></label><button class="button">Send request</button></form>':'<p>You do not manage another active organization that can be added to this photo.</p>')+'</section></main></body></html>';
}

